### ISSUE TITLE
sql-migrate does not support go modules is broken by v2 change

### ISSUE THREAD

**Issue by drscre** [posener/complete#107]
After v2 was merged directly into master (contrary to recommendations here https://blog.golang.org/v2-go-modules, section "Major version strategies"), some tools that (indirectly) rely on posener/complete and do no require module support broke.

https://github.com/rubenv/sql-migrate/issues/155

**Comment by posener** [comment]
Sorry about that, thanks for reporting this, continuing the conversation in the sql-migrate thread.

**Comment by posener** [comment]
Fixed by having the default branch on v1.
