### ISSUE TITLE
Support specifying the completion command

### ISSUE THREAD

**Issue by pwittrock** [posener/complete#113]
As an alternative to inferring the completion command from the binary, allow the command to be specified.

This is necessary for using a subcommand as a the completion command.

**Comment by posener** [comment]
Hi

Can you give an example to what you're trying to do? And what version you are using?
The `Complete` function do accept a name argument.

**Comment by pwittrock** [comment]
Sure!  I am using this library in [kustomize](https://github.com/kubernetes-sigs/kustomize/) for completion.

The library is great, but ideally I could make the completion command a subcommand of kustomize -- e.g. `kustomize complete`.  In this case the completion command would be something like `/Users/pwittrock/go/bin/kustomize completion --`.

.bash_profile would then include:

```sh
complete -C '/Users/pwittrock/go/bin/kustomize complete --' kustomize
```

IIUC, the name argument passed in to `Complete` is for the command being *completed*, so if I pass in `kustomize complete --` I get:

```sh
complete -C /Users/pwittrock/go/bin/kustomize kustomize complete --
```

**Comment by posener** [comment]
Hi
I see what you mean. I've seen a similar completion pattern a python CLI library back in the days.
I would first ask a reason why not using complete in the standard way with environment variables?
If this is indeed needed, we can refactor the [Complete](https://github.com/posener/complete/blob/master/complete.go#L61), and extract `CompleteLine( c Completer, line sting, point int)`.

WDYT?

**Comment by pwittrock** [comment]
@posener Thanks for being open to making changes.

I don't think environment variables solve the problem, let me know if I am wrong and there is some way to do it.  This issue is that *the program is self completing -- i.e. the program being completed is the same one as serving the completion suggestions*.

I'm using cobra to write the cli, which has a number of sub commands.

* Running `kustomize` without any subcommands should print the usage for `kustomize`.
* Running `kustomize config` should run the config subcommand. 
* The completion code should be bundled with `kustomize` in the same binary

Example workflow:

1. User installs `kustomize` using `go install`
  * `go install sigs.k8s.io/kustomize/kustomize/v3`
2. User installs completion -- this can be with the environment variable or not, I don't have a strong opinion on it.  The non-environment variable makes it easier to print help messaging, but not a big deal.
  * `COMP_INSTALL=1 kustomize` -- this is fine
  * `kustomize install-completion` -- this is also fine
3. User reloads their shell
  * `source ~/.bashrc`
4. User gets tab completion for sub commands
  * `kustomize config`

IIUC, the way complete works is that it invokes kustomize bare from the commandline:

`complete -C /Users/pwittrock/go/bin/kustomize kustomize`

If the program is being invoked for completion by the shell, then I want to invoke the completion logic.  However if the program is invoked by the user, I want to print the usage for the subcommand, or run the subcommand.

I've worked around this by looking at the arguments when the program starts, and trying to infer which context it is being invoked from.

I'd much prefer for the context to be explicit -- e.g. either from the shell for completion, or from the user to run the command.

**Comment by posener** [comment]
Regarding installation with `kustomize install-completion`, you can choose to use the [install package](https://github.com/posener/complete/blob/master/install/install.go) API.

When the program is being invoked for completion purposes, there will be non empty `COMP_LINE` and `COMP_POINT` environment variables.

This library was designed that in any case, you should just call `complete.Complete()` - if the current program was invoked in completion context, the completion will be executed and the the program will exit. If it was standard program context, calling `complete.Complete()` is a no-op.

Does this make sense?

**Comment by pwittrock** [comment]
Awesome.  I didn't see that API.  Yes that makes sense.  Thanks a lot!
