### ISSUE TITLE
Sensible line wrap length for comments

### ISSUE THREAD

**Issue by AdamSLevy** [posener/complete#116]
Feel free to close this immediately for being pedantic, however the comments in this package are not line wrapped at a sensible length. This is extremely annoying to work with in a terminal editor. This is totally a style choice, but I hate having to read comments in vim that go beyond 80 chars in length on a single line.

**Comment by AdamSLevy** [comment]
Beyond the annoyance of these comments when working on the files, this also makes reading the docs on the CLI quite annoying as well.
![example-bad-formatting](https://user-images.githubusercontent.com/6133616/75583860-f25c3480-5a1a-11ea-9043-175bf0fd2e3c.png)

**Comment by posener** [comment]
They are wrapped at 100 characters per line. Can you adjust to that?

**Comment by AdamSLevy** [comment]
Most terminals, historically and through to today, are around 80 characters in width. This may be inherited from days of yore where punch cards were a thing, but it persists to this day, and actually in practice, long lines are shown to be harder to read. There is general consensus among those interested in typography and the presentation of text that 2-3 alphabets is generally a good line length for readability. 80 chars is just above three 26 character alphabets. https://markboulton.co.uk/journal/five-simple-steps-to-better-typography/ 

More pragmatically, more that 80 characters just doesn't work with my workflow, which virtually always involves two vertical terminal windows side-by-side that take up the entirety of the screen. I'd imagine this style of setup is not entirely uncommon. I have a large display, but two terminals open side by side are each about 90 characters in width. This is on a rather large display with normal sized font. Fitting 100 characters per line generally makes the font a little too squished. If you look around, virtually every CLI caps lines at about 80 chars. 

I use `go doc` on the CLI as part of my work flow. Lines that are hard wrapped like this are incredibly annoying to read. When I'm working on code, long lines are hard to read and work on. I never let my code or comments go beyond 80 chars on a single line. If this becomes restrictive to me, I either take advantage of gofmt to help nicely align things on new lines, or its an indication that I have too many nested scopes, and at least one is worth breaking out into a separate function. This is of course a subjective style choice, which is why I left the code alone in my PR, but comments, which are very much intended for a human audience at least part of the time in a terminal, deserve better formatting in my humble opinion. 

You may have a workflow that is not heavily CLI based, or perhaps you only ever use one terminal at a time, or perhaps you have a display and a font that looks good when you pack 100 chars on a line, but for me, and probably 80% of cli users out there, will expect a line length of 80 to be respected. 

I don't mean any disrespect here. I personally feel strongly about this style choice for my own code, but this is your project, your repo, and ultimately your call. I will acquiesce to the standards you set. But honestly 100 chars is 20 too long if you ask me. At minimum its at least 12 too long for my setup.

**Comment by posener** [comment]
OK, sorry, different repos have different line width, and there are no strict guidelines for that.
I'm closing this issue.

Sorry.
