### ISSUE TITLE
Global flags

### ISSUE THREAD

**Issue by imarsman** [posener/complete#148]
I recently switched to the current master branch of complete. Previously I was able to define global flags and have them suggested before I input any sub commands. Now they are skipped even though they are defined as Flags in the main command definition. I also define a Sub in the main command and noticed that the complete() function only seems to suggest leaf command options if there are no sub commands defined. I would like to be able to define global flags such as --verbose and have them suggested.

```go
case len(c.SubCmdList()) == 0:
		// No sub commands, parse flags and positional arguments.
		return c.suggestLeafCommandOptions(), nil
```

**Comment by imarsman** [comment]
Looking at the issue history I can see how global flags could intrude on completions in the wrong place. It would work to allow global flags if they could be acted on only if there were no other handled non-global flags present in the input. I have for the moment worked around the issue by using sub-commands with keys like "-o" and "-v". This is working. I really enjoy having tab completion work for flags compared to the v1 branch I was using.

Please close this issue if on balance things work well.

**Comment by posener** [comment]
Alright, thanks!
