### ISSUE TITLE
Should this work?

### ISSUE THREAD

**Issue by keynan** [posener/complete#34]
I build the below command, run `./<cmd> -complete`.
Then I type (in bash) `./<cmd> -na` <tab> and expect it to auto fill 'me'.
Should that work?

int main(){
	var name string
	flag.StringVar(&name, "name", "", "Give your name")

	cmp := complete.New(
		flag.Arg(0),
		complete.Command{
			Sub: complete.Commands{
					"sadface": complete.Command{

					},
			},
			Flags: complete.Flags{
				"name": complete.PredictAnything,
			},
		},
	)

	cmp.AddFlags(nil, "complete", "uncomplete")

	flag.Parse()

	fmt.Printf("%s %s %s", flag.Args()...)
	if cmp.Run() {
		return
	}

	if name == "" {
		fmt.Println("Your name is missing")
		os.Exit(1)
	}

	fmt.Println("Hi,", name)
}

**Comment by posener** [comment]
Please look at the examples, the key in the `Flags` struct should be "-name".
For isntance: https://github.com/posener/complete/blob/master/gocomplete/complete.go#L23

**Comment by keynan** [comment]
This is example code.... The self completing program link, end of the main readme, which fyi doesn't compile, it's out of date with the API.

**Comment by posener** [comment]
Thanks, will fix those
