### ISSUE TITLE
gocomplete -install doesn't appear to do anything

### ISSUE THREAD

**Issue by josharian** [posener/complete#36]
I did:

```bash
$ go get -u github.com/posener/complete/gocomplete
$ gocomplete -install
# restart shell
$ go bui<tab>
```

Result: No completion.

From a cursory scan of the source, `gocomplete -install` should have prompted me, but it did not. Is it possible that the completer for `go install` is somehow interfering with the request for installation?

Thanks, and looking forward to using this.

**Comment by posener** [comment]
Thanks for that!
