### ISSUE TITLE
Complete packages names?

### ISSUE THREAD

**Issue by Deleplace** [posener/complete#41]
Hello, I am pretty exicted by the "Complete packages names" feature, which is exactly what I'm looking for.
I assume it should work on any fully qualified package name that resides inside $GOPATH (which would default to ~/go if $GOPATH is not set).

Unfortunately, I couldn't make it work:
`go build github.c`:repeat_one:
`go test github.com/gorilla/mu`:repeat_one:

...no results. I have tried with and without GOPATH set, even after starting new bash.
Any idea?

**Comment by posener** [comment]
Hi,
Thanks for this issue,
This could be fix by adding the go paths to the searched directories here: https://github.com/posener/complete/blob/master/gocomplete/pkgs.go#L25
Do you want to fix this?

**Comment by Deleplace** [comment]
I can give it a try :)

2017-07-12 7:22 GMT+02:00 Eyal Posener <notifications@github.com>:

**Comment by Deleplace** [comment]
Thank you for this Eyal!
Sorry about taking much time on my side, I actually wrote some code to get this working, but the whole folder/package duality is hard to get right at first attempt. Your code is better and also gives great results on my linux bash.

**Comment by posener** [comment]
Thanks for the feedback, no worries.
I saw your fork and understood the difficulties, my code is too messy :-)

**Comment by Deleplace** [comment]
Here are a few further remarks : 
- gocomplete now handles env var `GOPATH`, and is already aware that it may contain several directories :+1: 
- I suspect (not 100% sure) that in the Windows world a multiple-dir `GOPATH` would have entries separated by `os.PathListSeparator`, not by ":"
- the unit tests [fail when `GOPATH` is not set](https://gist.github.com/Deleplace/277812527e056f625e4f4b7a9e23ee37)
- gocomplete doesn't seem to handle `$HOME/go` (resp. `%USERPROFILE%\go`) as default (implicit) gopath when env var `GOPATH` is not set.

The implicit default gopath (since 1.8, see [rationale here](https://github.com/golang/go/issues/17262)) is a really super-extra-neat convention imo, we sure try to handle it.

Please expect a PR within 15mn, to address the 3 caveats.
