### ISSUE TITLE
Autocomplete subcommands even with nonexistent command

### ISSUE THREAD

**Issue by dadgar** [posener/complete#51]
Hey,

I noticed this bug when helping out with the other PRs. The autocomplete library can autocomplete a subcommand even if the given arguments wouldn't result in a valid command.

The issue stems from here: https://github.com/posener/complete/blob/master/command.go#L75-L76

For example `nomad job` has these subcommands:
```
$ nomad job
This command is accessed by using one of the subcommands below.

Subcommands:
    deployments    List deployments for a job
    dispatch       Dispatch an instance of a parameterized job
    history        Display all tracked versions of a job
    promote        Promote a job's canaries
    revert         Revert to a prior version of the job
    status         Display status information about a job
```

If I write: `$ nomad job nonexistent stat<tab>` it will autocomplete which is incorrect.

It is because the loop iterates till it finds a match, but really should give up if the argument leads to an incorrect subcommand.

**Comment by posener** [comment]
Hi @dadgar ,
Let's discuss this issue,
What happens is that the completion tries greedily find the next completion.
- First, it meets the subcommand `job` and goes into all it's completions.
- Then, it meets `nonexistant` which it assumes it's a `job` subcommand flag or whatever.
- The state still remains at the `job` subcommand, it still continue to the next words to find next subcommand, flags or incomplete words.
- Now it meets `stat` which it tries to complete according to the last subcommand it met, `job`, which is the current completion state.

For me it make sense,
What would you thought that the behavior should be? complete nothing?

**Comment by dadgar** [comment]
I would probably keep the scan but if the argument is neither a subcommand or a flag I would return.

**Comment by posener** [comment]
I am a bit afraid that we could loose here cases where the command expect some flags or arguments before a sub command.
Does it disturb, or bring any harm, that the completion still complete words, even if the whole command is wrong?

**Comment by dadgar** [comment]
Wouldn't checking the flags and global do the trick? It doesn't bother me just noticed the bug and thought I'd report it

**Comment by posener** [comment]
Hi @dadgar ,
for example, look at the following `git` command test case:
```bash
$ git log foo bar baz --a<TAB>
--abbrev=         --abbrev          --abbrev-commit   --after=          --all
```
even though foo bar baz, are three arguments, which are not branch names, or folders or files in my local repository, the git completion still tries to complete the flag.

Even: `$ git log foo bar baz orig<TAB>` completes to `$ git log foo bar baz origin/`...

**Comment by posener** [comment]
Ooops, didn't mean to close this issue :-D

**Comment by dadgar** [comment]
@posener Sure if it is the right behavior feel free to close.
