### ISSUE TITLE
File creation fails the moment a directory in the path is missing

### ISSUE THREAD

**Issue by walterdolce** [posener/complete#59]
I discovered this while using Hashicorp's Vault. Please see hashicorp/vault#4094 (https://github.com/hashicorp/vault/issues/4094#issuecomment-371197489) for more info.

Basically, I suspect the logic should first do a MkdirAll before creating a file. Otherwise, if the path contains a directory which is missing it would fail.

**Comment by posener** [comment]
Thanks for reporting!
Looks like an easy fix
