### ISSUE TITLE
Help with the self example

### ISSUE THREAD

**Issue by chinanf-boy** [posener/complete#61]
1. `go get`

2. `gocomplete -install`

3. `cd ..example/self && go run main.go -complete`

4. `$ self [Tab]` ❌
> compgen:96: no such file or directory: /var/folders/80/gh9snl2d35bcgh166p7jqs940000gn/T/go-build209898158/command-line-arguments/_obj/exe/main

**Comment by posener** [comment]
Hey
Stage 2 is not necessary, this one install bash completion for the go command line.
About stage 3: can you instead:
```bash
cd example/self
go install
self -complete
```

The self is installing self for completing it's own bash completion - the same binary is used for your program and for the bash completion, so it must be installed first and the binary itself is needed to install the completion (running the `self` binary with the `-complete` flag)

**Comment by chinanf-boy** [comment]
### Yes , I got it

``` bash
$ self [Tab] # output nothing
```

``` bash
$ self - [Tab] # -name : Right output
```

> Seem like - must be need `-`

**Comment by posener** [comment]
Yes, this is the current behavior of the completion.
Closing this. Thanks!
