### ISSUE TITLE
Support for COMP_POINT seems to have broken completion…

### ISSUE THREAD

**Issue by metacosm** [posener/complete#74]
```panic: runtime error: slice bounds out of range

goroutine 1 [running]:
.../vendor/github.com/posener/complete.(*Complete).Complete(0xc00038c690, 0x0)
	.../vendor/github.com/posener/complete/complete.go:67 +0x634
...
panic: runtime error: slice bounds out of range```

on tabbing for completion right after the name of the command. I haven't investigated closer but reverting to `1.1.2` fixes the issue.

**Comment by posener** [comment]
Hi,
Thanks for reporting.
Can you elaborate which command?
I tried `go<tab>` and `go build<tab>` and they both didn't panic for me.

**Comment by posener** [comment]
I see,
I don't understand why, but I can add protection to the slicing.

**Comment by metacosm** [comment]
@posener I've just checked, I think it also has to do with self-completion: you can exhibit the issue with your `self` example.

**Comment by posener** [comment]
Doesn't happen to me.
* Which shell do you use?
* Can you set export COMP_DEBUG=1 and reply with the stderr?
Thanks!

**Comment by metacosm** [comment]
I use zsh:
> zsh --version
zsh 5.3 (x86_64-apple-darwin18.0)

The code doesn't get to completion so `COMP_DEBUG` doesn't do anything, the error is the same as the one I've been getting (typing `./self` space then tab):

```
./self panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/posener/complete.(*Complete).Complete(0xc0000b0000, 0x0)
	/Users/claprun/Dev/go/src/github.com/posener/complete/complete.go:67 +0x634
main.main()
	/Users/claprun/Dev/go/src/github.com/posener/complete/example/self/main.go:42 +0x23f
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/posener/complete.(*Complete).Complete(0xc0000be000, 0x0)
	/Users/claprun/Dev/go/src/github.com/posener/complete/complete.go:67 +0x634
main.main()
	/Users/claprun/Dev/go/src/github.com/posener/complete/example/self/main.go:42 +0x23f
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/posener/complete.(*Complete).Complete(0xc000098000, 0x0)
	/Users/claprun/Dev/go/src/github.com/posener/complete/complete.go:67 +0x634
main.main()
	/Users/claprun/Dev/go/src/github.com/posener/complete/example/self/main.go:42 +0x23f```

**Comment by posener** [comment]
Yes, it panics before the first log.
OK, I'll just push the fix and we will see if this fixes your bug.

**Comment by metacosm** [comment]
Looks like it worked but it'd be interesting to know why that was happening… :/

**Comment by posener** [comment]
Sure,
You can add `Log("line: %s, point: %d", line, point)` before this line: https://github.com/posener/complete/blob/master/complete.go#L67.
Then run the code with `COMP_DEBUG=1`
We can see what the line and point values are, and why we got index out of range.
