### ISSUE TITLE
Cache results between completions 

### ISSUE THREAD

**Issue by millergarym** [posener/complete#81]
Is there a standard way of caching results (eg api call response) between completion calls.

The seemingly standard way of doing it in bash based completions is to used a global variable eg [1].
I understand this isn't technically an issue with this library. However it seems the appropriate place to ask the question.

[1]https://stackoverflow.com/questions/5327703/how-to-cache-a-variable-used-inside-a-bash-completion-script-for-the-current-ses

**Comment by posener** [comment]
Global variables will be useless since the application is loaded (main() is called) in every completion invocation.

I guess it depends in the use case. You could also use files for caching. Or, if you are qurying a local daemon, it could cache things.

**Comment by millergarym** [comment]
Landed up using a file with the ppid, cmd, subcmd & flag in the filename.
Also check the modtime of the file to invalidate the cache.

If this is a common use-case might be nice to include in the library.

**Comment by posener** [comment]
I thought of a single flie.
I think subcommand and flags are sufficient to determine the cache key.
Not sure what criteria you use to invalidate cache.
If you have a good api for caching, I'm open for suggestions.

**Comment by posener** [comment]
Closing as this became stale.
