### ISSUE TITLE
gocomplete go.mod should say "module github.com/posener/complete/gocomplete"

### ISSUE THREAD

**Issue by tv42** [posener/complete#88]
Trying to build gocomplete gives an error:

	go: finding github.com/posener/complete/gocomplete latest
	go: github.com/posener/complete/gocomplete@v0.0.0-20190308074557-af07aa5181b3: parsing go.mod: unexpected module path "gocomplete"
	go: error loading module requirements

**Comment by posener** [comment]
Thanks for that!

**Comment by posener** [comment]
Can you provide the command you've typed, go version and environment?

**Comment by tv42** [comment]
```
tv@dark ~$ mkdir z
tv@dark ~$ cd z
tv@dark ~/z$ go version
go version go1.12.5 linux/amd64
tv@dark ~/z$ go mod init m
go: creating new go.mod: module m
tv@dark ~/z$ go get github.com/posener/complete/gocomplete
go: finding github.com/posener/complete/gocomplete latest
go: github.com/posener/complete/gocomplete@v0.0.0-20190308074557-af07aa5181b3: parsing go.mod: unexpected module path "gocomplete"
go: error loading module requirements
[EXIT:1] tv@dark ~/z$
```

**Comment by posener** [comment]
I am not sure why you are trying to be dependent on `gocomplete` - as it is a main package.

The following command works fine:

```bash
go install github.com/posener/complete/gocomplete
```

Do you need more than that?

**Comment by tv42** [comment]
Because it's the standard way to control what versions get installed:
https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module

You may find that your bare `go install` command will also start failing in the future; your go.mod does not agree with that import path.

**Comment by posener** [comment]
I see, thanks for this!
