### ISSUE TITLE
[Proposal] Add IsInstalled API to posener/complete/cmd/install 

### ISSUE THREAD

**Issue by vadmeste** [posener/complete#89]
Hey,

I want from my tool which is using posener/complete to automatically show a yes/no prompt to request user's consent to install bash completion (or others). 

However it seems there is no way to avoid to show that prompt when completion is already installed. It seems the only way to do that is to to add IsInstalled() API.

I can send a PR for that if my proposal is accepted.

**Comment by posener** [comment]
Sorry for the delay. Sounds good. Go for it! :-)

**Comment by maxnordlund** [comment]
This would be sweet to have, as editing RC files is a bit surprising to say the least.
