### ISSUE TITLE
Autocomplete subcommand that has a same name as its parent doesn't work

### ISSUE THREAD

**Issue by recobe182** [posener/complete#97]
Consider this structure

	run := complete.Command{
		Sub: complete.Commands{
			"build": complete.Command{
				Sub: complete.Commands{
					"next":    complete.Command{},
					"forward": complete.Command{},
					"build":   complete.Command{},
				},
			},
		},
	}

	complete.New("app", run).Run()

When you try app build <tab> it should suggests three sub commands **next**, **forward** and **build** but it suggests nothing.

**Comment by posener** [comment]
Thanks,
Looking into it, it reproduces in a test when a sub command has the same name as its parent sub command. I'll look into it.
